### ISSUE TITLE
FYI - stream implementation used in Redis-Comander

### ISSUE THREAD

**Issue by sseide** [exocet-engineering/hfx-bus#4]
Hello,

just want to let you now that your implementation for stream support was used to add stream support to Redis-Commander, a redis web ui (https://github.com/joeferner/redis-commander/pull/351). The PR of the other user is not merged right now but will be soon.
(current WIP for integration: https://github.com/sseide/redis-commander/tree/streams)

I'll add some more license/copyright informations to the file at our project and will add a link back to your project from our readme. Hope its ok to use it (your license implies it). But just wanna let you know in case there are some objections or helpful hints...

Best regards,
Stefan Seide

**Comment by vflopes** [comment]
I am happy to contribute to the implementation and dissemination of Redis Streams, they deserve more popularity because they are really powerful and this will only happen with more support by the client libraries.

I have no objection, if you need help with something I am at your disposal!
